name: build

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - root/**
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - root/**
  repository_dispatch:
    types:
      - upstream_image_update

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TITLE: Red-DiscordBot
      GHCR_SLUG: ghcr.io/drapersniper/red-discordbot
      DOCK_SLUG: docker.io/drapersniper/red-discordbot
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GHCR_SLUG }}
            ${{ env.DOCK_SLUG }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push PyLav/latest
        uses: docker/build-push-action@v3
        with:
          target: pylav
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_SLUG }}:pylav
            ${{ env.DOCK_SLUG }}:pylav
            ${{ env.GHCR_SLUG }}:latest
            ${{ env.DOCK_SLUG }}:latest
          build-args: |
            PCX_DISCORDBOT_BUILD=${{ github.run_id }}
            PCX_DISCORDBOT_COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.GHCR_SLUG }}:pylav
      -
        name: Check pull
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.GHCR_SLUG }}:pylav
          docker image inspect ${{ env.GHCR_SLUG }}:pylav
          docker pull ${{ env.DOCK_SLUG }}:pylav
          docker image inspect ${{ env.DOCK_SLUG }}:pylav
